// Generated by `npm run types:generate` from the local database schema.
// Do not edit by hand: see scripts/generate-types.mts for the argument
// nullability widenings that are reapplied after every generation.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      digests: {
        Row: {
          created_at: string
          digest_date: string
          error: string | null
          id: string
          sent_at: string | null
          status: Database["public"]["Enums"]["digest_status"]
          telegram_message_id: number | null
          user_id: string
        }
        Insert: {
          created_at?: string
          digest_date: string
          error?: string | null
          id?: string
          sent_at?: string | null
          status: Database["public"]["Enums"]["digest_status"]
          telegram_message_id?: number | null
          user_id: string
        }
        Update: {
          created_at?: string
          digest_date?: string
          error?: string | null
          id?: string
          sent_at?: string | null
          status?: Database["public"]["Enums"]["digest_status"]
          telegram_message_id?: number | null
          user_id?: string
        }
        Relationships: []
      }
      learning_items: {
        Row: {
          added_at: string
          author: string | null
          built_at: string | null
          canonical_url: string
          content_type: Database["public"]["Enums"]["content_type"]
          created_at: string
          error: string | null
          failure_stage: Database["public"]["Enums"]["job_stage"] | null
          fetched_at: string | null
          id: string
          note: string | null
          provider_metadata: Json
          sorted_at: string | null
          source: Database["public"]["Enums"]["learning_source"]
          status: Database["public"]["Enums"]["learning_status"]
          title: string | null
          topic_id: string | null
          transcript: string | null
          updated_at: string
          url: string
          user_id: string
        }
        Insert: {
          added_at?: string
          author?: string | null
          built_at?: string | null
          canonical_url: string
          content_type: Database["public"]["Enums"]["content_type"]
          created_at?: string
          error?: string | null
          failure_stage?: Database["public"]["Enums"]["job_stage"] | null
          fetched_at?: string | null
          id?: string
          note?: string | null
          provider_metadata?: Json
          sorted_at?: string | null
          source: Database["public"]["Enums"]["learning_source"]
          status?: Database["public"]["Enums"]["learning_status"]
          title?: string | null
          topic_id?: string | null
          transcript?: string | null
          updated_at?: string
          url: string
          user_id: string
        }
        Update: {
          added_at?: string
          author?: string | null
          built_at?: string | null
          canonical_url?: string
          content_type?: Database["public"]["Enums"]["content_type"]
          created_at?: string
          error?: string | null
          failure_stage?: Database["public"]["Enums"]["job_stage"] | null
          fetched_at?: string | null
          id?: string
          note?: string | null
          provider_metadata?: Json
          sorted_at?: string | null
          source?: Database["public"]["Enums"]["learning_source"]
          status?: Database["public"]["Enums"]["learning_status"]
          title?: string | null
          topic_id?: string | null
          transcript?: string | null
          updated_at?: string
          url?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_items_topic_owner_fk"
            columns: ["topic_id", "user_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      learning_jobs: {
        Row: {
          attempts: number
          created_at: string
          id: string
          item_id: string | null
          last_error: string | null
          locked_at: string | null
          locked_by: string | null
          max_attempts: number
          payload: Json
          run_after: string
          stage: Database["public"]["Enums"]["job_stage"]
          status: Database["public"]["Enums"]["job_status"]
          topic_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          id?: string
          item_id?: string | null
          last_error?: string | null
          locked_at?: string | null
          locked_by?: string | null
          max_attempts?: number
          payload?: Json
          run_after?: string
          stage: Database["public"]["Enums"]["job_stage"]
          status?: Database["public"]["Enums"]["job_status"]
          topic_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          attempts?: number
          created_at?: string
          id?: string
          item_id?: string | null
          last_error?: string | null
          locked_at?: string | null
          locked_by?: string | null
          max_attempts?: number
          payload?: Json
          run_after?: string
          stage?: Database["public"]["Enums"]["job_stage"]
          status?: Database["public"]["Enums"]["job_status"]
          topic_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_jobs_item_owner_fk"
            columns: ["item_id", "user_id"]
            isOneToOne: false
            referencedRelation: "learning_items"
            referencedColumns: ["id", "user_id"]
          },
          {
            foreignKeyName: "learning_jobs_topic_owner_fk"
            columns: ["topic_id", "user_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string | null
          id: string
          timezone: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          id: string
          timezone?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          id?: string
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      quiz_attempts: {
        Row: {
          artifact_id: string
          completed_at: string
          created_at: string
          id: string
          score: number
          topic_id: string
          total_questions: number
          user_id: string
        }
        Insert: {
          artifact_id: string
          completed_at?: string
          created_at?: string
          id?: string
          score: number
          topic_id: string
          total_questions: number
          user_id: string
        }
        Update: {
          artifact_id?: string
          completed_at?: string
          created_at?: string
          id?: string
          score?: number
          topic_id?: string
          total_questions?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "quiz_attempts_artifact_owner_fk"
            columns: ["artifact_id", "user_id"]
            isOneToOne: false
            referencedRelation: "topic_artifacts"
            referencedColumns: ["id", "user_id"]
          },
          {
            foreignKeyName: "quiz_attempts_topic_owner_fk"
            columns: ["topic_id", "user_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      telegram_connections: {
        Row: {
          chat_id: number
          connected_at: string
          id: string
          telegram_first_name: string | null
          telegram_last_name: string | null
          telegram_username: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          chat_id: number
          connected_at?: string
          id?: string
          telegram_first_name?: string | null
          telegram_last_name?: string | null
          telegram_username?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          chat_id?: number
          connected_at?: string
          id?: string
          telegram_first_name?: string | null
          telegram_last_name?: string | null
          telegram_username?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      telegram_link_tokens: {
        Row: {
          created_at: string
          expires_at: string
          id: string
          token_hash: string
          used_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          expires_at: string
          id?: string
          token_hash: string
          used_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          expires_at?: string
          id?: string
          token_hash?: string
          used_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      topic_artifacts: {
        Row: {
          content_json: Json | null
          content_markdown: string | null
          created_at: string
          id: string
          is_current: boolean
          kind: Database["public"]["Enums"]["artifact_kind"]
          model: string | null
          source_item_ids: string[]
          topic_id: string
          user_id: string
          version: number
        }
        Insert: {
          content_json?: Json | null
          content_markdown?: string | null
          created_at?: string
          id?: string
          is_current?: boolean
          kind: Database["public"]["Enums"]["artifact_kind"]
          model?: string | null
          source_item_ids?: string[]
          topic_id: string
          user_id: string
          version: number
        }
        Update: {
          content_json?: Json | null
          content_markdown?: string | null
          created_at?: string
          id?: string
          is_current?: boolean
          kind?: Database["public"]["Enums"]["artifact_kind"]
          model?: string | null
          source_item_ids?: string[]
          topic_id?: string
          user_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "topic_artifacts_topic_owner_fk"
            columns: ["topic_id", "user_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      topics: {
        Row: {
          created_at: string
          id: string
          name: string
          normalized_name: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          normalized_name: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          normalized_name?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      user_settings: {
        Row: {
          created_at: string
          daily_item_limit: number
          digest_enabled: boolean
          digest_hour: number
          onboarded_at: string | null
          timezone: string
          updated_at: string
          user_id: string
          youtube_capture_enabled: boolean
          youtube_last_polled_at: string | null
          youtube_playlist_id: string | null
        }
        Insert: {
          created_at?: string
          daily_item_limit?: number
          digest_enabled?: boolean
          digest_hour?: number
          onboarded_at?: string | null
          timezone?: string
          updated_at?: string
          user_id: string
          youtube_capture_enabled?: boolean
          youtube_last_polled_at?: string | null
          youtube_playlist_id?: string | null
        }
        Update: {
          created_at?: string
          daily_item_limit?: number
          digest_enabled?: boolean
          digest_hour?: number
          onboarded_at?: string | null
          timezone?: string
          updated_at?: string
          user_id?: string
          youtube_capture_enabled?: boolean
          youtube_last_polled_at?: string | null
          youtube_playlist_id?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      claim_learning_jobs: {
        Args: { p_limit: number; p_worker_id: string }
        Returns: {
          attempts: number
          created_at: string
          id: string
          item_id: string | null
          last_error: string | null
          locked_at: string | null
          locked_by: string | null
          max_attempts: number
          payload: Json
          run_after: string
          stage: Database["public"]["Enums"]["job_stage"]
          status: Database["public"]["Enums"]["job_status"]
          topic_id: string | null
          updated_at: string
          user_id: string
        }[]
        SetofOptions: {
          from: "*"
          to: "learning_jobs"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      complete_classify_job: {
        Args: {
          p_existing_topic_id?: string | null
          p_job_id: string
          p_normalized_name: string
          p_topic_name: string
          p_worker_id: string
        }
        Returns: Database["public"]["Enums"]["learning_status"]
      }
      complete_digest_job: {
        Args: {
          p_digest_date: string
          p_job_id: string
          p_status: Database["public"]["Enums"]["digest_status"]
          p_telegram_message_id?: number | null
          p_worker_id: string
        }
        Returns: Database["public"]["Enums"]["job_status"]
      }
      complete_fetch_job: {
        Args: {
          p_author: string | null
          p_job_id: string
          p_provider_metadata?: Json
          p_title: string | null
          p_transcript: string
          p_worker_id: string
        }
        Returns: Database["public"]["Enums"]["learning_status"]
      }
      complete_maintenance_job: {
        Args: {
          p_job_id: string
          p_update_playlist_poll_time?: boolean
          p_worker_id: string
        }
        Returns: Database["public"]["Enums"]["job_status"]
      }
      complete_topic_build: {
        Args: {
          p_briefing: Json
          p_model: string
          p_quiz: Json
          p_source_item_ids: string[]
          p_study_guide: Json
          p_topic_id: string
          p_user_id: string
        }
        Returns: Json
      }
      complete_topic_build_job: {
        Args: {
          p_briefing: Json
          p_job_id: string
          p_model: string
          p_quiz: Json
          p_source_item_ids: string[]
          p_study_guide: Json
          p_worker_id: string
        }
        Returns: Json
      }
      connect_telegram_with_token: {
        Args: {
          p_chat_id: number
          p_telegram_first_name?: string
          p_telegram_last_name?: string
          p_telegram_username?: string
          p_token: string
        }
        Returns: string
      }
      create_learning_item_for_current_user: {
        Args: {
          p_canonical_url: string
          p_content_type: Database["public"]["Enums"]["content_type"]
          p_note?: string | null
          p_provider_metadata?: Json
          p_source: Database["public"]["Enums"]["learning_source"]
          p_url: string
        }
        Returns: {
          item_id: string
          was_created: boolean
        }[]
      }
      create_learning_item_for_user: {
        Args: {
          p_canonical_url: string
          p_content_type: Database["public"]["Enums"]["content_type"]
          p_note?: string | null
          p_provider_metadata?: Json
          p_source: Database["public"]["Enums"]["learning_source"]
          p_url: string
          p_user_id: string
        }
        Returns: {
          item_id: string
          was_created: boolean
        }[]
      }
      create_telegram_link_token: {
        Args: { p_ttl?: string }
        Returns: {
          expires_at: string
          token: string
        }[]
      }
      enqueue_due_maintenance_jobs: {
        Args: never
        Returns: {
          digest_jobs_created: number
          playlist_jobs_created: number
        }[]
      }
      enqueue_playlist_sync_for_current_user: { Args: never; Returns: string }
      fail_learning_job: {
        Args: {
          p_error: string
          p_job_id: string
          p_payload_patch?: Json
          p_retryable: boolean
          p_worker_id: string
        }
        Returns: Database["public"]["Enums"]["job_status"]
      }
      get_digest_context: {
        Args: { p_job_id: string; p_worker_id: string }
        Returns: Json
      }
      invoke_process_learning_jobs: { Args: never; Returns: number }
      record_quiz_attempt: {
        Args: {
          p_artifact_id: string
          p_score: number
          p_total_questions: number
        }
        Returns: string
      }
      requeue_stale_jobs: {
        Args: { p_lock_timeout?: string }
        Returns: {
          dead_count: number
          requeued_count: number
        }[]
      }
      retry_learning_item: {
        Args: { p_item_id: string }
        Returns: {
          job_id: string
          retry_stage: Database["public"]["Enums"]["job_stage"]
        }[]
      }
    }
    Enums: {
      artifact_kind: "study_guide" | "briefing" | "quiz"
      content_type: "youtube" | "article"
      digest_status: "sent" | "skipped" | "failed"
      job_stage:
        | "fetch"
        | "classify"
        | "build_topic"
        | "capture_playlist"
        | "digest"
      job_status: "queued" | "running" | "succeeded" | "failed" | "dead"
      learning_source: "telegram" | "web" | "youtube_playlist" | "manual"
      learning_status: "new" | "fetched" | "sorted" | "done" | "failed"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      artifact_kind: ["study_guide", "briefing", "quiz"],
      content_type: ["youtube", "article"],
      digest_status: ["sent", "skipped", "failed"],
      job_stage: [
        "fetch",
        "classify",
        "build_topic",
        "capture_playlist",
        "digest",
      ],
      job_status: ["queued", "running", "succeeded", "failed", "dead"],
      learning_source: ["telegram", "web", "youtube_playlist", "manual"],
      learning_status: ["new", "fetched", "sorted", "done", "failed"],
    },
  },
} as const

