/**
 * Regenerates src/types/database.ts from the running local database.
 *
 *   npx supabase start && npm run types:generate
 *
 * `supabase gen types` reads argument types from pg_proc, which records no
 * nullability for function arguments, so every argument comes out non-nullable.
 * Several of our RPCs genuinely take NULL — an article with no byline, a capture
 * with no note, a digest that was skipped rather than sent. This script reapplies
 * exactly those widenings so the file stays reproducible instead of hand-edited.
 *
 * A widening that no longer matches is a hard failure: the schema changed and
 * the list below needs revisiting.
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface Widening {
  argument: string;
  type: string;
  occurrences: number;
  reason: string;
}

const WIDENINGS: Widening[] = [
  { argument: "p_title", type: "string", occurrences: 1, reason: "fetched content may have no title" },
  { argument: "p_author", type: "string", occurrences: 1, reason: "fetched content may have no byline" },
  { argument: "p_note?", type: "string", occurrences: 2, reason: "a capture may carry no note" },
  {
    argument: "p_existing_topic_id?",
    type: "string",
    occurrences: 1,
    reason: "classification may not match an existing topic",
  },
  {
    argument: "p_telegram_message_id?",
    type: "number",
    occurrences: 1,
    reason: "a skipped digest sends no message",
  },
];

const OUTPUT = resolve(process.cwd(), "src/types/database.ts");

function generate(): string {
  // execSync goes through a shell, which is what makes the npx shim work on
  // Windows as well as POSIX. Every argument here is a constant.
  return execSync("npx supabase gen types typescript --local --schema public", {
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
    stdio: ["ignore", "pipe", "inherit"],
  });
}

function applyWidenings(source: string): string {
  return WIDENINGS.reduce((current, { argument, type, occurrences, reason }) => {
    const search = `          ${argument}: ${type}\n`;
    const found = current.split(search).length - 1;

    if (found !== occurrences) {
      throw new Error(
        `Expected ${occurrences} occurrence(s) of "${argument}: ${type}" (${reason}) but found ${found}. ` +
          "The schema changed; update scripts/generate-types.mts.",
      );
    }

    return current.split(search).join(`          ${argument}: ${type} | null\n`);
  }, source);
}

const header = [
  "// Generated by `npm run types:generate` from the local database schema.",
  "// Do not edit by hand: see scripts/generate-types.mts for the argument",
  "// nullability widenings that are reapplied after every generation.",
  "",
].join("\n");

writeFileSync(OUTPUT, header + applyWidenings(generate()), "utf8");
console.log(`Wrote ${OUTPUT}`);
